//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Forms_Weather_Forecast.ForecastGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForecastGenerator.IForecastGenerationService")]
    public interface IForecastGenerationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecastGenerationService/GenerateForecast", ReplyAction="http://tempuri.org/IForecastGenerationService/GenerateForecastResponse")]
        Weather_Forecast_Models.WeatherForecastViewModel[] GenerateForecast(int numberOfDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IForecastGenerationService/GenerateForecast", ReplyAction="http://tempuri.org/IForecastGenerationService/GenerateForecastResponse")]
        System.Threading.Tasks.Task<Weather_Forecast_Models.WeatherForecastViewModel[]> GenerateForecastAsync(int numberOfDays);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IForecastGenerationServiceChannel : Web_Forms_Weather_Forecast.ForecastGenerator.IForecastGenerationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ForecastGenerationServiceClient : System.ServiceModel.ClientBase<Web_Forms_Weather_Forecast.ForecastGenerator.IForecastGenerationService>, Web_Forms_Weather_Forecast.ForecastGenerator.IForecastGenerationService {
        
        public ForecastGenerationServiceClient() {
        }
        
        public ForecastGenerationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ForecastGenerationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecastGenerationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ForecastGenerationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Weather_Forecast_Models.WeatherForecastViewModel[] GenerateForecast(int numberOfDays) {
            return base.Channel.GenerateForecast(numberOfDays);
        }
        
        public System.Threading.Tasks.Task<Weather_Forecast_Models.WeatherForecastViewModel[]> GenerateForecastAsync(int numberOfDays) {
            return base.Channel.GenerateForecastAsync(numberOfDays);
        }
    }
}
